---

- name: create config folder
  file:
    path: /etc/tor/torrc.d/
    state: directory
    mode: 0755
  become: yes

- name: enable torrc.d
  lineinfile:
    path: /etc/tor/torrc
    line: '%include /etc/tor/torrc.d/'
  become: yes
  notify: restart_tor
